disable executable build

diff --git a/.github/workflows/linux-standalone-build.yaml b/.github/workflows/linux-standalone-build.yaml
--- a/.github/workflows/linux-standalone-build.yaml
+++ b/.github/workflows/linux-standalone-build.yaml
@@ -78,79 +78,79 @@ jobs:
         run: |
           echo "FFmpeg already built"
           bash ${{ env.SOURCE_DIR }}/build-script/build-static-ffmpeg.sh --no-build
-          
-      - name: Build Qt Statically
-        if: steps.cache-qt.outputs.cache-hit != 'true'
-        run: |
-          bash ${{ env.SOURCE_DIR }}/build-script/build-static-qt-from-source.sh
 
-      - name: Create build directory
-        run: |
-          mkdir ${{ runner.temp }}/build
+      # - name: Build Qt Statically
+      #   if: steps.cache-qt.outputs.cache-hit != 'true'
+      #   run: |
+      #     bash ${{ env.SOURCE_DIR }}/build-script/build-static-qt-from-source.sh
 
-      - name: Prepare Driver Files
-        run: |
-          mkdir ${{ env.SOURCE_DIR }}/drivers
-          cp driver/linux/* ${{ env.SOURCE_DIR }}/drivers/
+      # - name: Create build directory
+      #   run: |
+      #     mkdir ${{ runner.temp }}/build
+
+      # - name: Prepare Driver Files
+      #   run: |
+      #     mkdir ${{ env.SOURCE_DIR }}/drivers
+      #     cp driver/linux/* ${{ env.SOURCE_DIR }}/drivers/
       
-      - name: Install OpenGL ES Development Packages
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y \
-            libgles2-mesa-dev \
-            libegl1-mesa-dev \
-            libglib2.0-dev \
-            libpcre2-dev \
-            libxrandr2 \
-            libxcb1-dev \
-            '^libxcb.*-dev' \
-            libx11-xcb-dev \
-            libglu1-mesa-dev \
-            libxrender-dev \
-            libxi-dev \
-            libxkbcommon-dev \
-            libxkbcommon-x11-dev \
-            libexpat-dev \
-            libfreetype6-dev \
-            libfontconfig1-dev \
-            libx11-dev \
-            libdbus-1-dev \
-            libdbus-glib-1-dev \
-            libpulse-dev \
-            libsndfile1-dev
+      # - name: Install OpenGL ES Development Packages
+      #   run: |
+      #     sudo apt-get update
+      #     sudo apt-get install -y \
+      #       libgles2-mesa-dev \
+      #       libegl1-mesa-dev \
+      #       libglib2.0-dev \
+      #       libpcre2-dev \
+      #       libxrandr2 \
+      #       libxcb1-dev \
+      #       '^libxcb.*-dev' \
+      #       libx11-xcb-dev \
+      #       libglu1-mesa-dev \
+      #       libxrender-dev \
+      #       libxi-dev \
+      #       libxkbcommon-dev \
+      #       libxkbcommon-x11-dev \
+      #       libexpat-dev \
+      #       libfreetype6-dev \
+      #       libfontconfig1-dev \
+      #       libx11-dev \
+      #       libdbus-1-dev \
+      #       libdbus-glib-1-dev \
+      #       libpulse-dev \
+      #       libsndfile1-dev
 
 
-      - name: Build Standalone Executable
-        working-directory: ${{ runner.temp }}/build
-        run: |
-          echo "Setting LD_LIBRARY_PATH..."
-          export LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH
+      # - name: Build Standalone Executable
+      #   working-directory: ${{ runner.temp }}/build
+      #   run: |
+      #     echo "Setting LD_LIBRARY_PATH..."
+      #     export LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH
 
-          echo "Configuring with CMake..."
-          cmake -S "${{ env.SOURCE_DIR }}" -B . \
-              -DCMAKE_BUILD_TYPE=Release \
-              -DBUILD_SHARED_LIBS=OFF \
-              -DCMAKE_PREFIX_PATH=/opt/Qt6 \
-              -DCMAKE_INSTALL_PREFIX=release \
-              -DCMAKE_VERBOSE_MAKEFILE=ON
+      #     echo "Configuring with CMake..."
+      #     cmake -S "${{ env.SOURCE_DIR }}" -B . \
+      #         -DCMAKE_BUILD_TYPE=Release \
+      #         -DBUILD_SHARED_LIBS=OFF \
+      #         -DCMAKE_PREFIX_PATH=/opt/Qt6 \
+      #         -DCMAKE_INSTALL_PREFIX=release \
+      #         -DCMAKE_VERBOSE_MAKEFILE=ON
 
-          cat CMakeFiles/openterfaceQT.dir/link.txt
-          echo "Building with CMake..."
-          cmake --build . || (echo "CMake build failed. Please check the build configuration." && exit 1)
+      #     cat CMakeFiles/openterfaceQT.dir/link.txt
+      #     echo "Building with CMake..."
+      #     cmake --build . || (echo "CMake build failed. Please check the build configuration." && exit 1)
 
-          if [ ! -f release/openterfaceQT ]; then
-            echo "Error: Failed to build openterfaceQT"
-            exit 1
-          fi
+      #     if [ ! -f release/openterfaceQT ]; then
+      #       echo "Error: Failed to build openterfaceQT"
+      #       exit 1
+      #     fi
 
-          echo "Creating standalone package..."
-          mkdir package
-          cp release/openterfaceQT package
+      #     echo "Creating standalone package..."
+      #     mkdir package
+      #     cp release/openterfaceQT package
 
-      - name: Save build artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ env.ARTIFACT }}
-          path: ${{ runner.temp }}/build/package/openterfaceQT
-          if-no-files-found: error
+      # - name: Save build artifact
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: ${{ env.ARTIFACT }}
+      #     path: ${{ runner.temp }}/build/package/openterfaceQT
+      #     if-no-files-found: error
 
