Add debug log

diff --git a/.github/workflows/linux-flatpak-build.yaml b/.github/workflows/linux-flatpak-build.yaml
--- a/.github/workflows/linux-flatpak-build.yaml
+++ b/.github/workflows/linux-flatpak-build.yaml
@@ -48,6 +48,11 @@ jobs:
           flatpak install --user --noninteractive flathub org.kde.Sdk/${{ matrix.arch }}/6.7
           flatpak install --user --noninteractive flathub org.kde.Platform/${{ matrix.arch }}/6.7
       
+      - name: Debug Qt Environment
+        run: |
+          flatpak run org.kde.Sdk//6.7 sh -c "which qmake && qmake --version || echo 'qmake not found'"
+          flatpak run org.kde.Sdk//6.7 sh -c "which lupdate && lupdate --version || echo 'lupdate not found'"
+
       - name: Initialize build directory
         run: |
           flatpak build-init ${{ env.FLATPAK_BUILD_DIR }} org.openterface.openterfaceQT org.kde.Sdk//6.7 org.kde.Platform//6.7 ${{ matrix.arch }}
