build deps

diff --git a/.github/workflows/linux-standalone-build.yaml b/.github/workflows/linux-standalone-build.yaml
--- a/.github/workflows/linux-standalone-build.yaml
+++ b/.github/workflows/linux-standalone-build.yaml
@@ -90,79 +90,79 @@ jobs:
         run: |
           mkdir ${{ runner.temp }}/build
 
-      - name: Prepare Driver Files
-        run: |
-          mkdir ${{ env.SOURCE_DIR }}/drivers
-          cp driver/linux/* ${{ env.SOURCE_DIR }}/drivers/
+      # - name: Prepare Driver Files
+      #   run: |
+      #     mkdir ${{ env.SOURCE_DIR }}/drivers
+      #     cp driver/linux/* ${{ env.SOURCE_DIR }}/drivers/
       
-      - name: Install Dependency Packages
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y \
-            libgles2-mesa-dev \
-            libegl1-mesa-dev \
-            libglib2.0-dev \
-            libpcre2-dev \
-            libxrandr2 \
-            libxcb1-dev \
-            '^libxcb.*-dev' \
-            libxcb-glx0-dev \
-            libx11-xcb-dev \
-            libglu1-mesa-dev \
-            libxrender-dev \
-            libxi-dev \
-            libxkbcommon-dev \
-            libxkbcommon-x11-dev \
-            libx11-dev \
-            libdbus-1-dev \
-            libdbus-glib-1-dev \
-            libpulse-dev \
-            libsndfile1-dev \
-            libxrandr-dev \
-            libxrender-dev
+      # - name: Install Dependency Packages
+      #   run: |
+      #     sudo apt-get update
+      #     sudo apt-get install -y \
+      #       libgles2-mesa-dev \
+      #       libegl1-mesa-dev \
+      #       libglib2.0-dev \
+      #       libpcre2-dev \
+      #       libxrandr2 \
+      #       libxcb1-dev \
+      #       '^libxcb.*-dev' \
+      #       libxcb-glx0-dev \
+      #       libx11-xcb-dev \
+      #       libglu1-mesa-dev \
+      #       libxrender-dev \
+      #       libxi-dev \
+      #       libxkbcommon-dev \
+      #       libxkbcommon-x11-dev \
+      #       libx11-dev \
+      #       libdbus-1-dev \
+      #       libdbus-glib-1-dev \
+      #       libpulse-dev \
+      #       libsndfile1-dev \
+      #       libxrandr-dev \
+      #       libxrender-dev
 
-      - name: Build Standalone Executable
-        working-directory: ${{ runner.temp }}/build
-        run: |
-          echo "Setting LD_LIBRARY_PATH..."
-          export LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH
+      # - name: Build Standalone Executable
+      #   working-directory: ${{ runner.temp }}/build
+      #   run: |
+      #     echo "Setting LD_LIBRARY_PATH..."
+      #     export LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH
 
-          echo "Configuring with CMake..."
-            cmake -S "${{ env.SOURCE_DIR }}" -B . \
-              -DCMAKE_BUILD_TYPE=Release \
-              -DBUILD_SHARED_LIBS=OFF \
-              -DCMAKE_PREFIX_PATH=/opt/Qt6 \
-              -DCMAKE_INSTALL_PREFIX=release \
-              -DCMAKE_VERBOSE_MAKEFILE=ON \
-              -DQT_DEBUG_FIND_PACKAGE=ON \
-              -DCMAKE_CXX_FLAGS="-Os -s" \
-              -DCMAKE_C_FLAGS="-Os -s" \
-              -DLINK_LIBUSB_STATICALLY=ON \
-              -DFREETYPE_INCLUDE_DIRS=/usr/include/freetype2 \
-              -DFREETYPE_LIBRARIES=/usr/lib/libfreetype.a \
-              -DFONTCONFIG_LIBRARIES=/usr/lib/libfontconfig.a \
-              -DEXPAT_LIBRARY_PATH=/usr/lib/libexpat.a \
-              -DLIBUSB_LIB=/usr/lib/libusb-1.0.a
+      #     echo "Configuring with CMake..."
+      #       cmake -S "${{ env.SOURCE_DIR }}" -B . \
+      #         -DCMAKE_BUILD_TYPE=Release \
+      #         -DBUILD_SHARED_LIBS=OFF \
+      #         -DCMAKE_PREFIX_PATH=/opt/Qt6 \
+      #         -DCMAKE_INSTALL_PREFIX=release \
+      #         -DCMAKE_VERBOSE_MAKEFILE=ON \
+      #         -DQT_DEBUG_FIND_PACKAGE=ON \
+      #         -DCMAKE_CXX_FLAGS="-Os -s" \
+      #         -DCMAKE_C_FLAGS="-Os -s" \
+      #         -DLINK_LIBUSB_STATICALLY=ON \
+      #         -DFREETYPE_INCLUDE_DIRS=/usr/include/freetype2 \
+      #         -DFREETYPE_LIBRARIES=/usr/lib/libfreetype.a \
+      #         -DFONTCONFIG_LIBRARIES=/usr/lib/libfontconfig.a \
+      #         -DEXPAT_LIBRARY_PATH=/usr/lib/libexpat.a \
+      #         -DLIBUSB_LIB=/usr/lib/libusb-1.0.a
               
-          echo "Building with CMake..."
-          cmake --build . --verbose || (echo "CMake build failed. Please check the build configuration." && exit 1)
+      #     echo "Building with CMake..."
+      #     cmake --build . --verbose || (echo "CMake build failed. Please check the build configuration." && exit 1)
 
-          if [ ! -f openterfaceQT ]; then
-            echo "Error: Failed to build openterfaceQT"
-            exit 1
-          fi
+      #     if [ ! -f openterfaceQT ]; then
+      #       echo "Error: Failed to build openterfaceQT"
+      #       exit 1
+      #     fi
 
-          echo "Check openterfaceQT dependencies..."
-          ldd openterfaceQT
+      #     echo "Check openterfaceQT dependencies..."
+      #     ldd openterfaceQT
 
-          echo "Creating standalone package..."
-          mkdir package
-          cp openterfaceQT package
+      #     echo "Creating standalone package..."
+      #     mkdir package
+      #     cp openterfaceQT package
 
-      - name: Save build artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ env.ARTIFACT }}
-          path: ${{ runner.temp }}/build/package/openterfaceQT
-          if-no-files-found: error
+      # - name: Save build artifact
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: ${{ env.ARTIFACT }}
+      #     path: ${{ runner.temp }}/build/package/openterfaceQT
+      #     if-no-files-found: error
 
