build 9

diff --git a/.github/workflows/linux-standalone-build.yaml b/.github/workflows/linux-standalone-build.yaml
--- a/.github/workflows/linux-standalone-build.yaml
+++ b/.github/workflows/linux-standalone-build.yaml
@@ -109,7 +109,7 @@ jobs:
 
           cat CMakeFiles/openterfaceQT.dir/link.txt
           echo "Building with CMake..."
-          cmake --trace-expand --build . || (echo "CMake build failed. Please check the build configuration." && exit 1)
+          cmake --build . || (echo "CMake build failed. Please check the build configuration." && exit 1)
 
           if [ ! -f release/openterfaceQT ]; then
             echo "Error: Failed to build openterfaceQT"
