Set path

diff --git a/.github/workflows/standalone-build.yaml b/.github/workflows/standalone-build.yaml
--- a/.github/workflows/standalone-build.yaml
+++ b/.github/workflows/standalone-build.yaml
@@ -45,6 +45,9 @@ jobs:
         run: |
           choco install mingw -y
           choco install ninja -y
+          echo "Setting up PATH for MinGW and Ninja"
+          set PATH=C:\ProgramData\chocolatey\bin;%PATH%
+          g++ --version || (echo "g++ installation failed. Please check the installation." && exit 1)
 
       - name: Build Qt Statically
         if: steps.cache-qt.outputs.cache-hit != 'true'
