Sync

diff --git a/.github/workflows/standalone-build.yaml b/.github/workflows/standalone-build.yaml
--- a/.github/workflows/standalone-build.yaml
+++ b/.github/workflows/standalone-build.yaml
@@ -75,50 +75,50 @@
             run: |
               mkdir ${{ runner.temp }}\build
               
-          - name: Prepare .pro File for Static Build
-            run: |
-              echo "Checking and appending static build configuration to .pro file..."
-              if not exist "${{ env.SOURCE_DIR }}\openterfaceQT.pro" (
-                echo "Error: .pro file not found."
-                exit 1
-              )
-              findstr /C:"CONFIG += static release" "${{ env.SOURCE_DIR }}\openterfaceQT.pro" >nul
-              if errorlevel 1 (
-                echo "CONFIG += static release" >> "${{ env.SOURCE_DIR }}\openterfaceQT.pro"
-                echo "QMAKE_LFLAGS += -static -static-libgcc -static-libstdc++ -static-libwinpthread" >> "${{ env.SOURCE_DIR }}\openterfaceQT.pro"
-                echo "Static build configuration added to .pro file."
-                set ERRORLEVEL=0  # Reset error level
-              ) else (
-                echo "Static build configuration already present in .pro file."
-              )
-          - name: Build Standalone Executable
-            working-directory: ${{ runner.temp }}\build
-            run: |
-              echo "Checking Qt configuration..."
-              C:\Qt6\bin\qmake -query
-              set PATH=C:\Qt6\bin;%PATH%
+        #   - name: Prepare .pro File for Static Build
+        #     run: |
+        #       echo "Checking and appending static build configuration to .pro file..."
+        #       if not exist "${{ env.SOURCE_DIR }}\openterfaceQT.pro" (
+        #         echo "Error: .pro file not found."
+        #         exit 1
+        #       )
+        #       findstr /C:"CONFIG += static release" "${{ env.SOURCE_DIR }}\openterfaceQT.pro" >nul
+        #       if errorlevel 1 (
+        #         echo "CONFIG += static release" >> "${{ env.SOURCE_DIR }}\openterfaceQT.pro"
+        #         echo "QMAKE_LFLAGS += -static -static-libgcc -static-libstdc++ -static-libwinpthread" >> "${{ env.SOURCE_DIR }}\openterfaceQT.pro"
+        #         echo "Static build configuration added to .pro file."
+        #         set ERRORLEVEL=0  # Reset error level
+        #       ) else (
+        #         echo "Static build configuration already present in .pro file."
+        #       )
+        #   - name: Build Standalone Executable
+        #     working-directory: ${{ runner.temp }}\build
+        #     run: |
+        #       echo "Checking Qt configuration..."
+        #       C:\Qt6\bin\qmake -query
+        #       set PATH=C:\Qt6\bin;%PATH%
               
-              echo "Building with qmake..."
+        #       echo "Building with qmake..."
               
-              dir /s C:\ProgramData\chocolatey\lib\mingw*
-              qmake -v
-              qmake -r "${{ env.SOURCE_DIR }}\openterfaceQT.pro" CONFIG+=release || (echo "qmake failed. Please check the .pro file and paths." && exit 1)
+        #       dir /s C:\ProgramData\chocolatey\lib\mingw*
+        #       qmake -v
+        #       qmake -r "${{ env.SOURCE_DIR }}\openterfaceQT.pro" CONFIG+=release || (echo "qmake failed. Please check the .pro file and paths." && exit 1)
             
-              echo "Building with mingw32-make..."
-              mingw32-make -j2 || (echo "mingw32-make failed. Please check the build configuration." && exit 1)
-              set ERRORLEVEL=0  # Reset error level after build
+        #       echo "Building with mingw32-make..."
+        #       mingw32-make -j2 || (echo "mingw32-make failed. Please check the build configuration." && exit 1)
+        #       set ERRORLEVEL=0  # Reset error level after build
               
-              if not exist release\openterfaceQT.exe (
-                echo "Error: Failed to build openterfaceQT.exe"
-                exit 1
-              )
+        #       if not exist release\openterfaceQT.exe (
+        #         echo "Error: Failed to build openterfaceQT.exe"
+        #         exit 1
+        #       )
             
-              echo "Creating standalone package..."
-              mkdir package
-              copy release\openterfaceQT.exe package
-          - name: Save build artifact
-            uses: actions/upload-artifact@v4
-            with:
-              name: ${{ env.ARTIFACT }}
-              path: ${{ runner.temp }}\build\package\openterfaceQT.exe
-              if-no-files-found: error 
+        #       echo "Creating standalone package..."
+        #       mkdir package
+        #       copy release\openterfaceQT.exe package
+        #   - name: Save build artifact
+        #     uses: actions/upload-artifact@v4
+        #     with:
+        #       name: ${{ env.ARTIFACT }}
+        #       path: ${{ runner.temp }}\build\package\openterfaceQT.exe
+        #       if-no-files-found: error 
