build again

diff --git a/.github/workflows/standalone-build.yaml b/.github/workflows/standalone-build.yaml
--- a/.github/workflows/standalone-build.yaml
+++ b/.github/workflows/standalone-build.yaml
@@ -96,7 +96,7 @@
               echo "Building with qmake..."
               
               qmake -v
-              qmake -r "${{ env.SOURCE_DIR }}\openterfaceQT.pro" CONFIG+=release || (echo "qmake failed. Please check the .pro file and paths." && exit 1)
+              qmake -r "${{ env.SOURCE_DIR }}\openterfaceQT.pro" || (echo "qmake failed. Please check the .pro file and paths." && exit 1)
 
               echo "Building with mingw32-make..."
               mingw32-make VERBOSE=1 -j2 || (echo "mingw32-make failed. Please check the build configuration." && exit 1)
