change qmake

diff --git a/.github/workflows/standalone-build.yaml b/.github/workflows/standalone-build.yaml
--- a/.github/workflows/standalone-build.yaml
+++ b/.github/workflows/standalone-build.yaml
@@ -69,22 +69,6 @@ jobs:
         run: |
           mkdir ${{ runner.temp }}\build
           
-      - name: Prepare .pro File for Static Build
-        run: |
-          echo "Checking and appending static build configuration to .pro file..."
-          if (-Not (Test-Path "${{ env.SOURCE_DIR }}\openterfaceQT.pro")) {
-            Write-Host "Error: .pro file not found."
-            exit 1
-          }
-          $content = Get-Content "${{ env.SOURCE_DIR }}\openterfaceQT.pro"
-          if ($content -notcontains "CONFIG += static release") {
-            Add-Content "${{ env.SOURCE_DIR }}\openterfaceQT.pro" "CONFIG += static release"
-            Add-Content "${{ env.SOURCE_DIR }}\openterfaceQT.pro" "QMAKE_LFLAGS += -static"
-            Write-Host "Static build configuration added to .pro file."
-          } else {
-            Write-Host "Static build configuration already present in .pro file."
-          }
-
       - name: Build Standalone Executable
         working-directory: ${{ runner.temp }}\build
         run: |
@@ -95,7 +79,7 @@ jobs:
           set PATH=C:\Qt6\bin;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;%PATH%
 
           qmake -v
-          qmake -r "${{ env.SOURCE_DIR }}\openterfaceQT.pro" CONFIG+=release || (echo "qmake failed. Please check the .pro file and paths." && exit 1)
+          qmake -r "${{ env.SOURCE_DIR }}\openterfaceQT.pro" -static CONFIG+=static release || (echo "qmake failed. Please check the .pro file and paths." && exit 1)
         
           echo "Building with mingw32-make..."
           mingw32-make -j2 || (echo "mingw32-make failed. Please check the build configuration." && exit 1)
