Fix bug (#201)
* Add cmake local build for linux, and rectify error name whitch in the Cmakelist

* Fix the numpad key do not work in keyboard input. (#63)

* Fix the paste issue.

* use define declare the server_port

* Dev 20250310 fix virus error (#64)

* Test for the windows protable

* Add the strip command

* Del some useless file

* Change the .pro file, using the static build

* test

* static lib test

* cahgne the static-libgfortran

* Change the windows build git pull action

* Bump version to 0.2.1.070

---------

Co-authored-by: GitHub Action <action@github.com>

* Dev 20250310 fix virus error (#65)

* Test for the windows protable

* Add the strip command

* Del some useless file

* Change the .pro file, using the static build

* test

* static lib test

* cahgne teh static-libgfortran

* Change the windows build git pull action

* Bump version to 0.2.1.070

* Change the code fix the linux build error.

---------

Co-authored-by: GitHub Action <action@github.com>

---------

Co-authored-by: GitHub Action <action@github.com>

diff --git a/.github/workflows/windows-portable-build.yaml b/.github/workflows/windows-portable-build.yaml
--- a/.github/workflows/windows-portable-build.yaml
+++ b/.github/workflows/windows-portable-build.yaml
@@ -17,6 +17,7 @@
     SOURCE_DIR: ${{ github.workspace }}
     QT_VERSION: 6.5.3 
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    ORGANIZATION_NAME: "TechxArtisan"
   
   jobs:
     build:
@@ -92,7 +93,7 @@
               echo "Static build configuration already present in .pro file."
             )
             
-            echo "QMAKE_LFLAGS += -static -static-libgcc -static-libstdc++ -static-libwinpthread" >> "${{ env.SOURCE_DIR }}\openterfaceQT.pro"
+            echo "QMAKE_LFLAGS += -static -static-libgcc -static-libstdc++ -static-libgfortran" >> "${{ env.SOURCE_DIR }}\openterfaceQT.pro"
             echo "QMAKE_CXXFLAGS += -static -static-libgcc -static-libstdc++" >> "${{ env.SOURCE_DIR }}\openterfaceQT.pro"
             echo "QMAKE_LINK = g++ -Wl,-subsystem,windows" >> "${{ env.SOURCE_DIR }}\openterfaceQT.pro"
             echo "CONFIG += static staticlib" >> "${{ env.SOURCE_DIR }}\openterfaceQT.pro"
@@ -107,6 +108,7 @@
             echo "Checking Qt configuration..."
             C:\Qt6\bin\qmake -query
             set PATH=C:\Qt6\bin;C:\mingw64\bin;%PATH%
+            set INCLUDE=C:\Qt6\include;%INCLUDE%
             
             echo "Building with qmake..."
             
@@ -121,6 +123,9 @@
               exit 1
             )
           
+            echo "Stripping debug symbols from executable..."
+            strip -s release\openterfaceQT.exe || (echo "Failed to strip debug symbols" && exit 1)
+            
             echo "Creating portable package..."
             mkdir package
             copy release\openterfaceQT.exe package
