Optimize Windows build workflow by adding caching for Qt and MinGW, and streamline installation steps for a static build environment

diff --git a/.github/workflows/windows-build.yaml b/.github/workflows/windows-build.yaml
--- a/.github/workflows/windows-build.yaml
+++ b/.github/workflows/windows-build.yaml
@@ -50,21 +50,47 @@ jobs:
         with:
           fetch-depth: 0
 
+            
+      - name: Cache Qt Build
+        id: cache-qt
+        uses: actions/cache@v3
+        with:
+            path: C:\Qt6
+            key: qt-6.5.3-mingw-windows-static
+            restore-keys: |
+              qt-6.5.3-mingw-windows-static
+
+      - name: Cache MinGW and Ninja Build
+        id: cache-mingw
+        uses: actions/cache@v3
+        with:
+          path: |
+            C:\mingw64
+            C:\ProgramData\chocolatey\lib\ninja
+          key: mingw-ninja-windows-static
+          restore-keys: |
+            mingw-ninja-windows-static
+            
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
           python-version: '3.10'
 
-      - name: Cache Qt
-        id: cache-qt
-        uses: actions/cache@v3
-        with:
-          path: ${{ runner.temp }}/Qt
-          key: ${{ env.QT_CACHE_KEY }}
-          restore-keys: |
-            ${{ env.QT_CACHE_KEY }}
-            qt-6.5-mingw-windows
-
+      - name: Install Build environment
+        if: steps.cache-mingw.outputs.cache-hit != 'true'
+        run: |
+          echo "Installing Ninja"
+          choco install ninja -y
+    
+          echo "Downloading pre-compiled static build of MinGW-w64"
+          curl -L -o mingw-w64.zip https://sourceforge.net/projects/mingw-w64/files/latest/download
+          mkdir C:\mingw-w64
+          tar -xf mingw-w64.zip -C C:\mingw64 --strip-components=1
+    
+          echo "Setting up PATH for MinGW-w64"
+          set PATH=C:\mingw64\bin;%PATH%
+          g++ --version || (echo "g++ installation failed. Please check the installation." && exit 1)
+  
       - name: Update version
         run: |
           if [ "${{ github.event.inputs.increase_version }}" = "true" ]; then
@@ -83,29 +109,29 @@ jobs:
         run: |
           git fetch --all --tags -f
 
-      - name: Install Qt
-        if: steps.cache-qt.outputs.cache-hit != 'true'
-        uses: jurplel/install-qt-action@v4
-        with:
-          version: ${{ env.QT_VERSION }}
-          host: windows
-          target: desktop
-          arch: win64_mingw
-          dir: ${{ runner.temp }}
-          modules: qtmultimedia qtserialport
-          setup-python: false
+      # - name: Install Qt
+      #   if: steps.cache-qt.outputs.cache-hit != 'true'
+      #   uses: jurplel/install-qt-action@v4
+      #   with:
+      #     version: ${{ env.QT_VERSION }}
+      #     host: windows
+      #     target: desktop
+      #     arch: win64_mingw
+      #     dir: ${{ runner.temp }}
+      #     modules: qtmultimedia qtserialport
+      #     setup-python: false
 
-      - name: Download and Unzip Jom
-        if: steps.cache-jom.outputs.cache-hit != 'true'
-        working-directory: ${{ runner.temp }}
-        run: |
-          curl -L -o jom.zip "http://download.qt.io/official_releases/jom/jom.zip"
-          7z x jom.zip -ojom
+      # - name: Download and Unzip Jom
+      #   if: steps.cache-jom.outputs.cache-hit != 'true'
+      #   working-directory: ${{ runner.temp }}
+      #   run: |
+      #     curl -L -o jom.zip "http://download.qt.io/official_releases/jom/jom.zip"
+      #     7z x jom.zip -ojom
 
-      - name: Set up Visual Studio shell
-        uses: egor-tensin/vs-shell@v2
-        with:
-          arch: x64
+      # - name: Set up Visual Studio shell
+      #   uses: egor-tensin/vs-shell@v2
+      #   with:
+      #     arch: x64
       
       - name: Build Qt Statically
         if: steps.cache-qt.outputs.cache-hit != 'true'
